apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-from-a
spec:
  podSelector:
    matchLabels:
      word-picker: "a"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          word-picker: "a"
  