apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: A Simple WordPicker application
  name: word-picker-template
parameters:
- name: APP_POSTFIX
  description: This string is added to the end of the resource names
  required: true
- name: CUSTOM_OPTIONS
  description: The words in this string are going to be the options for the application.
  value: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
- name: REPLICAS
  description: The replica count for the word-picker deployment
  value: "2"
- name: CUSTOM_LABEL_NAME
  description: The name of the custom label applied to all resources
  value: "word-picker"
- name: CUSTOM_LABEL_VALUE
  description: The value of the custom label applied to all resources
  value: "word-picker"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: word-picker-${APP_POSTFIX}
      ${CUSTOM_LABEL_NAME}: ${CUSTOM_LABEL_VALUE}
    name: word-picker-options-${APP_POSTFIX}
  data:
    custom_options.txt: ${CUSTOM_OPTIONS} 
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: word-picker-${APP_POSTFIX}
    labels:
      app: word-picker-${APP_POSTFIX}
      ${CUSTOM_LABEL_NAME}: ${CUSTOM_LABEL_VALUE}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: word-picker-${APP_POSTFIX}
        ${CUSTOM_LABEL_NAME}: ${CUSTOM_LABEL_VALUE}
    template:
      metadata:
        labels:
          app: word-picker-${APP_POSTFIX}
          ${CUSTOM_LABEL_NAME}: ${CUSTOM_LABEL_VALUE}
      spec:
        containers:
        - name: word-picker
          image: tinmancoding/word-picker:v2.11
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          volumeMounts:
          - name: options-config-map
            mountPath: /code/config
          env:
          - name: OPTIONS_FILE
            value: /code/config/custom_options.txt
        volumes:
        - name: options-config-map
          configMap:
            name: word-picker-options-${APP_POSTFIX}
- apiVersion: v1
  kind: Service
  metadata:
    name: word-picker-${APP_POSTFIX}
  spec:
    type: ClusterIP
    selector:
      app: word-picker-${APP_POSTFIX}
      ${CUSTOM_LABEL_NAME}: ${CUSTOM_LABEL_VALUE}
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000

