apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: word-picker
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: tinmancoding/word-picker:v1
    importPolicy:
      importMode: Legacy
      scheduled: true
    referencePolicy:
      type: Local
  - name: staging
    from:
      kind: DockerImage
      name: tinmancoding/word-picker:v1
    importPolicy:
      importMode: Legacy
      scheduled: true
    referencePolicy:
      type: Local
  - name: production
    from:
      kind: DockerImage
      name: tinmancoding/word-picker:v1
    importPolicy:
      importMode: Legacy
      scheduled: true
    referencePolicy:
      type: Local
        